[FEAT] swap crypto disclaimer
bitpay/wallet pull request #11804
Opened 2021-08-09 22:35 UTC by JohnathanWhite

2021-08-14 16:56 UTC, mrbaguvix requested changes

2021-08-14 16:56 UTC, mrbaguvix commented on src/components/info-sheet/info-sheet.html
> +        The Swap Crypto function is provided by Changelly and 1Inch, and subject to the service providers' terms and conditions, which you accept by using the service. Use of the Swap Crypto function
If this are services "Changelly", "1Inch", It would be better if they're emphasized or a link to their domain would be much better.

2021-08-16 20:08 UTC, Gamboster commented on src/pages/home/home.ts
> +  public createInfoSheet(type: InfoSheetType, params?): InfoSheetComponent {
This should be a `private` function

2021-08-16 20:09 UTC, Gamboster commented on src/pages/home/home.ts
> +  public goToSwapCryptoPage() {
With the changes, this should be a `private` function also

2021-08-16 20:47 UTC, Gamboster commented
Looks good, just a few small comments.. and needs rebase

2021-08-17 00:47 UTC, JohnathanWhite commented on src/pages/home/home.ts
> +  public createInfoSheet(type: InfoSheetType, params?): InfoSheetComponent {
thanks good catches

2021-08-17 00:54 UTC, Gamboster approved these changes
ACK

2021-08-17 00:55 UTC, merged